// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NaeTime.Persistence.SQLite.Context;

#nullable disable

namespace NaeTime.Persistence.SQLite.Migrations
{
    [DbContext(typeof(NaeTimeDbContext))]
    [Migration("20240214225620_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.ActiveSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ActiveSession");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.ActiveTimings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Lane")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("LapNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActiveTimings");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.Detection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("HardwareTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Lane")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SoftwareTime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TimerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UtcTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Detections");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.EthernetLapRF8Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("IpAddress")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EthernetLapRF8Channels");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.Lane", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("BandId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RadioFrequencyInMhz")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Lanes");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.OpenPracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("MaximumLapMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinimumLapMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OpenPracticeSessions");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.Pilot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.TimerStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConnectionStatusChanged")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasConnected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TimerStatuses");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("AllowedLanes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaximumLapMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinimumLapMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.ActiveTimings", b =>
                {
                    b.OwnsOne("NaeTime.Persistence.SQLite.Models.ActiveLap", "ActiveLap", b1 =>
                        {
                            b1.Property<Guid>("ActiveTimingsId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<ulong?>("StartedHardwareTime")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("StartedSoftwareTime")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("StartedUtcTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("ActiveTimingsId");

                            b1.ToTable("ActiveTimings");

                            b1.WithOwner()
                                .HasForeignKey("ActiveTimingsId");
                        });

                    b.OwnsOne("NaeTime.Persistence.SQLite.Models.ActiveSplit", "ActiveSplit", b1 =>
                        {
                            b1.Property<Guid>("ActiveTimingsId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<byte>("SplitNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("StartedSoftwareTime")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("StartedUtcTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("ActiveTimingsId");

                            b1.ToTable("ActiveTimings");

                            b1.WithOwner()
                                .HasForeignKey("ActiveTimingsId");
                        });

                    b.Navigation("ActiveLap");

                    b.Navigation("ActiveSplit");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.OpenPracticeSession", b =>
                {
                    b.OwnsMany("NaeTime.Persistence.SQLite.Models.ConsecutiveLapLeaderboard", "ConsecutiveLapLeaderboards", b1 =>
                        {
                            b1.Property<Guid>("OpenPracticeSessionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<uint>("ConsecutiveLaps")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OpenPracticeSessionId", "Id");

                            b1.ToTable("ConsecutiveLapLeaderboard");

                            b1.WithOwner()
                                .HasForeignKey("OpenPracticeSessionId");

                            b1.OwnsMany("NaeTime.Persistence.SQLite.Models.ConsecutiveLapLeaderboardPosition", "Positions", b2 =>
                                {
                                    b2.Property<Guid>("ConsecutiveLapLeaderboardOpenPracticeSessionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("ConsecutiveLapLeaderboardId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<DateTime>("LastLapCompletionUtc")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("PilotId")
                                        .HasColumnType("TEXT");

                                    b2.Property<uint>("Position")
                                        .HasColumnType("INTEGER");

                                    b2.Property<uint>("TotalLaps")
                                        .HasColumnType("INTEGER");

                                    b2.Property<long>("TotalMilliseconds")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("ConsecutiveLapLeaderboardOpenPracticeSessionId", "ConsecutiveLapLeaderboardId", "Id");

                                    b2.ToTable("ConsecutiveLapLeaderboardPosition");

                                    b2.WithOwner()
                                        .HasForeignKey("ConsecutiveLapLeaderboardOpenPracticeSessionId", "ConsecutiveLapLeaderboardId");

                                    b2.OwnsMany("NaeTime.Persistence.SQLite.Models.ConsecutiveLapLeaderboardPositionLap", "IncludedLaps", b3 =>
                                        {
                                            b3.Property<Guid>("ConsecutiveLapLeaderboardPositionConsecutiveLapLeaderboardOpenPracticeSessionId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("ConsecutiveLapLeaderboardPositionConsecutiveLapLeaderboardId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("ConsecutiveLapLeaderboardPositionId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("LapId")
                                                .HasColumnType("TEXT");

                                            b3.Property<int>("Ordinal")
                                                .HasColumnType("INTEGER");

                                            b3.HasKey("ConsecutiveLapLeaderboardPositionConsecutiveLapLeaderboardOpenPracticeSessionId", "ConsecutiveLapLeaderboardPositionConsecutiveLapLeaderboardId", "ConsecutiveLapLeaderboardPositionId", "Id");

                                            b3.ToTable("ConsecutiveLapLeaderboardPositionLap");

                                            b3.WithOwner()
                                                .HasForeignKey("ConsecutiveLapLeaderboardPositionConsecutiveLapLeaderboardOpenPracticeSessionId", "ConsecutiveLapLeaderboardPositionConsecutiveLapLeaderboardId", "ConsecutiveLapLeaderboardPositionId");
                                        });

                                    b2.Navigation("IncludedLaps");
                                });

                            b1.Navigation("Positions");
                        });

                    b.OwnsMany("NaeTime.Persistence.SQLite.Models.OpenPracticeLap", "Laps", b1 =>
                        {
                            b1.Property<Guid>("OpenPracticeSessionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("FinishedUtc")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("PilotId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("StartedUtc")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("TotalMilliseconds")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OpenPracticeSessionId", "Id");

                            b1.ToTable("OpenPracticeLap");

                            b1.WithOwner()
                                .HasForeignKey("OpenPracticeSessionId");
                        });

                    b.OwnsMany("NaeTime.Persistence.SQLite.Models.PilotLane", "ActiveLanes", b1 =>
                        {
                            b1.Property<Guid>("OpenPracticeSessionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<byte>("Lane")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("PilotId")
                                .HasColumnType("TEXT");

                            b1.HasKey("OpenPracticeSessionId", "Id");

                            b1.ToTable("PilotLane");

                            b1.WithOwner()
                                .HasForeignKey("OpenPracticeSessionId");
                        });

                    b.OwnsMany("NaeTime.Persistence.SQLite.Models.SingleLapLeaderboard", "SingleLapLeaderboards", b1 =>
                        {
                            b1.Property<Guid>("OpenPracticeSessionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.HasKey("OpenPracticeSessionId", "Id");

                            b1.ToTable("SingleLapLeaderboard");

                            b1.WithOwner()
                                .HasForeignKey("OpenPracticeSessionId");

                            b1.OwnsMany("NaeTime.Persistence.SQLite.Models.SingleLapLeaderboardPosition", "Positions", b2 =>
                                {
                                    b2.Property<Guid>("SingleLapLeaderboardOpenPracticeSessionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("SingleLapLeaderboardId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<DateTime>("CompletionUtc")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("LapId")
                                        .HasColumnType("TEXT");

                                    b2.Property<long>("LapMilliseconds")
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("PilotId")
                                        .HasColumnType("TEXT");

                                    b2.Property<uint>("Position")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("SingleLapLeaderboardOpenPracticeSessionId", "SingleLapLeaderboardId", "Id");

                                    b2.ToTable("SingleLapLeaderboardPosition");

                                    b2.WithOwner()
                                        .HasForeignKey("SingleLapLeaderboardOpenPracticeSessionId", "SingleLapLeaderboardId");
                                });

                            b1.Navigation("Positions");
                        });

                    b.Navigation("ActiveLanes");

                    b.Navigation("ConsecutiveLapLeaderboards");

                    b.Navigation("Laps");

                    b.Navigation("SingleLapLeaderboards");
                });

            modelBuilder.Entity("NaeTime.Persistence.SQLite.Models.Track", b =>
                {
                    b.OwnsMany("NaeTime.Persistence.SQLite.Models.TrackTimer", "Timers", b1 =>
                        {
                            b1.Property<Guid>("TrackId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("TimerId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TrackId", "Id");

                            b1.ToTable("TrackTimer");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("Timers");
                });
#pragma warning restore 612, 618
        }
    }
}
