// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NaeTime.Persistence.EntityFramework;

#nullable disable

namespace NaeTime.Persistence.SQLite.Migrations
{
    [DbContext(typeof(NaeTimeDbContext))]
    [Migration("20250413130158_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.ActiveSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ActiveSession");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.ActiveTimings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Lane")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("LapNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActiveTimings");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.AverageLapLeaderboardPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FirstLapCompletionUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AverageLapLeaderboardPositions");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.ConsecutiveLapLeaderboardPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<uint>("LapCap")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLapCompletionUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("TotalLaps")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConsecutiveLapLeaderboardPositions");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.Detection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("HardwareTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Lane")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SoftwareTime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TimerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UtcTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Detections");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.EthernetLapRF8Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("IpAddress")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EthernetLapRF8Channels");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.LapRFLaneConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ushort?>("ActualGain")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("ActualThreshold")
                        .HasColumnType("REAL");

                    b.Property<ushort?>("DesiredGain")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("DesiredThreshold")
                        .HasColumnType("REAL");

                    b.Property<byte>("Lane")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LapRFConfigurations");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.NodeLaneConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ushort?>("ActualEntryThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("ActualExitThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("DesiredEntryThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("DesiredExitThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Lane")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NodeLaneConfigurations");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.OpenPracticeLaneConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte?>("BandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrequencyInMhz")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Lane")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OpenPracticeLaneConfigurations");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.OpenPracticeLap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OpenPracticeLaps");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.OpenPracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("MaximumLapMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinimumLapMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OpenPracticeSessions");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.Pilot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.SerialEsp32Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Port")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SerialEsp32Nodes");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.SingleLapLeaderboardPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletionUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LapId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SingleLapLeaderboardPositions");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.SystemLaneConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte?>("BandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("LaneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SystemLaneConfigurations");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.TimerLaneConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte?>("ActualBandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualFrequencyInMhz")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ActualIsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("DesiredBandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DesiredFrequencyInMhz")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DesiredIsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("LaneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TimerLaneConfigurations");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.TimerStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConnectionStatusChanged")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TimerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasConnected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TimerStatuses");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.TotalLapsLeaderboardPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstLapCompletionUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalLaps")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TotalLapsLeaderboardPositions");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("AllowedLanes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaximumLapMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinimumLapMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.ActiveTimings", b =>
                {
                    b.OwnsOne("NaeTime.Persistence.EntityFramework.Models.ActiveLap", "ActiveLap", b1 =>
                        {
                            b1.Property<Guid>("ActiveTimingsId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<ulong?>("StartedHardwareTime")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("StartedSoftwareTime")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("StartedUtcTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("ActiveTimingsId");

                            b1.ToTable("ActiveTimings");

                            b1.WithOwner()
                                .HasForeignKey("ActiveTimingsId");
                        });

                    b.OwnsOne("NaeTime.Persistence.EntityFramework.Models.ActiveSplit", "ActiveSplit", b1 =>
                        {
                            b1.Property<Guid>("ActiveTimingsId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<byte>("SplitNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("StartedSoftwareTime")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("StartedUtcTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("ActiveTimingsId");

                            b1.ToTable("ActiveTimings");

                            b1.WithOwner()
                                .HasForeignKey("ActiveTimingsId");
                        });

                    b.Navigation("ActiveLap");

                    b.Navigation("ActiveSplit");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.ConsecutiveLapLeaderboardPosition", b =>
                {
                    b.OwnsMany("NaeTime.Persistence.EntityFramework.Models.IncludedLap", "IncludedLaps", b1 =>
                        {
                            b1.Property<Guid>("ConsecutiveLapLeaderboardPositionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("LapId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ConsecutiveLapLeaderboardPositionId", "Id");

                            b1.ToTable("IncludedLap");

                            b1.WithOwner()
                                .HasForeignKey("ConsecutiveLapLeaderboardPositionId");
                        });

                    b.Navigation("IncludedLaps");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.OpenPracticeSession", b =>
                {
                    b.OwnsMany("NaeTime.Persistence.EntityFramework.Models.TrackedConsecutiveLaps", "TrackedConsecutiveLaps", b1 =>
                        {
                            b1.Property<Guid>("OpenPracticeSessionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<uint>("LapCap")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OpenPracticeSessionId", "Id");

                            b1.ToTable("TrackedConsecutiveLaps");

                            b1.WithOwner()
                                .HasForeignKey("OpenPracticeSessionId");
                        });

                    b.Navigation("TrackedConsecutiveLaps");
                });

            modelBuilder.Entity("NaeTime.Persistence.EntityFramework.Models.Track", b =>
                {
                    b.OwnsMany("NaeTime.Persistence.EntityFramework.Models.TrackTimer", "Timers", b1 =>
                        {
                            b1.Property<Guid>("TrackId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("TimerId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TrackId", "Id");

                            b1.ToTable("TrackTimer");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("Timers");
                });
#pragma warning restore 612, 618
        }
    }
}
