<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventDb.Sqlite\EventDb.Sqlite.csproj" />
    <ProjectReference Include="..\..\EventDbLite.Reactions.SignalR.Server\EventDbLite.Reactions.SignalR.Server.csproj" />
    <ProjectReference Include="..\..\EventDbLite\EventDbLite.csproj" />
    <ProjectReference Include="..\..\NaeTime.Announcer\NaeTime.Announcer.csproj" />
    <ProjectReference Include="..\..\NaeTime.Client\NaeTime.Client.csproj" />
    <ProjectReference Include="..\..\NaeTime.Command\NaeTime.Command.csproj" />
    <ProjectReference Include="..\..\NaeTime.Hardware.ImmersionRC\NaeTime.Hardware.ImmersionRC.csproj" />
    <ProjectReference Include="..\..\NaeTime.Hardware.Node.Esp32\NaeTime.Hardware.Node.Esp32.csproj" />
    <ProjectReference Include="..\..\NaeTime.Hardware\NaeTime.Hardware.csproj" />
    <ProjectReference Include="..\..\NaeTime.Query\NaeTime.Query.csproj" />
    <ProjectReference Include="..\..\NaeTime.Reactions\NaeTime.Reactions.csproj" />
    <ProjectReference Include="..\NaeTime.Client.BlazorWebApp.Client\NaeTime.Client.BlazorWebApp.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0" />
    <PackageReference Include="System.Speech" Version="10.0.1" />
  </ItemGroup>

</Project>
