<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NaeTime.Orchestrator.Persistence.Abstractions\NaeTime.Orchestrator.Persistence.Abstractions.csproj" />
    <ProjectReference Include="..\NaeTime.Persistence.EntityFramework\NaeTime.Persistence.EntityFramework.csproj" />
  </ItemGroup>

</Project>
