<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Pages\HardwarePages\HardwareList.razor" />
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.Bootstrap" Version="3.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.3" />
    <PackageReference Include="Syncfusion.Blazor.Calendars" Version="28.2.12" />
    <PackageReference Include="Syncfusion.Blazor.Charts" Version="28.2.12" />
    <PackageReference Include="Syncfusion.Blazor.Inputs" Version="28.2.12" />
    <PackageReference Include="Syncfusion.Blazor.LinearGauge" Version="28.2.12" />
    <PackageReference Include="Syncfusion.Blazor.Popups" Version="28.2.12" />
    <PackageReference Include="Syncfusion.Blazor.RichTextEditor" Version="28.2.12" />
    <PackageReference Include="Syncfusion.Blazor.Sparkline" Version="28.2.12" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="28.2.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NaeTime.Client.Configuration\NaeTime.Client.Configuration.csproj" />
    <ProjectReference Include="..\NaeTime.Client.Razor.Lib\NaeTime.Client.Razor.Lib.csproj" />
    <ProjectReference Include="..\NaeTime.Hardware.ImmersionRC\NaeTime.Hardware.ImmersionRC.csproj" />
    <ProjectReference Include="..\NaeTime.Hardware.Messages\NaeTime.Hardware.Messages.csproj" />
    <ProjectReference Include="..\NaeTime.Hardware\NaeTime.Hardware.csproj" />
    <ProjectReference Include="..\NaeTime.Management.Messages\NaeTime.Management.Messages.csproj" />
    <ProjectReference Include="..\NaeTime.OpenPractice.Messages\NaeTime.OpenPractice.Messages.csproj" />
    <ProjectReference Include="..\NaeTime.Persistence.Abstractions\NaeTime.Persistence.Abstractions.csproj" />
    <ProjectReference Include="..\NaeTime.PubSub.Abstractions\NaeTime.PubSub.Abstractions.csproj" />
    <ProjectReference Include="..\NaeTime.Timing.Messages\NaeTime.Timing.Messages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Timing\" />
  </ItemGroup>

</Project>
