<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
	    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
		    <_Parameter1>EventDbLite.Tests</_Parameter1>
	    </AssemblyAttribute>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.9" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\EventDbLite.Reactions.Abstractions\EventDbLite.Reactions.Abstractions.csproj" />
      <ProjectReference Include="..\EventDbLite.Serialization\EventDbLite.Serialization.csproj" />
      <ProjectReference Include="..\NaeTime.SQLite\NaeTime.SQLite.csproj" />
    </ItemGroup>
</Project>
