public enum RecordType : ushort
{
    TUNE_LANE = 0x01,
    CONFIGURE_NODE = 0x02,
    NODE_STATUS = 0x03,
    CONFIGURE_LANE_ENTRY_THRESHOLD = 0x04,
    CONFIGURE_LANE_EXIT_THRESHOLD = 0x05,
    CONFIGURE_LANE_ENABLED = 0x06,
    REQUEST_LANE_CONFIGURATIONS = 0x07,
    LANE_PASS_EVENT = 0x08,

    RESPONSE = 0xFC,
    STATUS = 0xFD,
    ERROR = 0xFE,
    ACK = 0xFF
};