public enum RecordType : ushort
{
    TUNE_LANE = 0x01,
    CONFIGURE_NODE = 0x02,
    NODE_TIMINGS = 0x03,
    CONFIGURE_LANE_ENTRY_THRESHOLD = 0x04,
    CONFIGURE_LANE_EXIT_THRESHOLD = 0x05,

    ERROR = 0xFE,
    ACK = 0xFF
};