<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
	<PackageReference Include="MudBlazor" Version="8.15.0" />
	<PackageReference Include="Toolbelt.Blazor.SpeechSynthesis" Version="10.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventDbLite\EventDbLite.Reactions.Abstractions\EventDbLite.Reactions.Abstractions.csproj" />
    <ProjectReference Include="..\..\EventDbLite\EventDbLite.Reactions.SignalR.Client\EventDbLite.Reactions.SignalR.Client.csproj" />
    <ProjectReference Include="..\..\EventDbLite\EventDbLite\EventDbLite.csproj" />
    <ProjectReference Include="..\..\NaeTime.Announcer\NaeTime.Announcer.csproj" />
    <ProjectReference Include="..\..\NaeTime.Client\NaeTime.Client.csproj" />
    <ProjectReference Include="..\..\NaeTime.Command.Abstractions\NaeTime.Command.Abstractions.csproj" />
    <ProjectReference Include="..\..\NaeTime.Query.Abstractions\NaeTime.Query.Abstractions.csproj" />
  </ItemGroup>

</Project>
