namespace NaeTime.Events;

public record OpenPracticePilotTimingStarted(Guid PilotId, Guid SessionId, Guid TrackId, Guid[] TrackDetectors, long? RedetectionDelayMilliseconds, long? MaximumLapMilliseconds);

public record OpenPracticePilotDetectionOccured(Guid DetectionId, Guid SessionId, Guid TrackId, Guid PilotId, Guid TimerId, byte TrackTimerOrdinal, byte TrackTimerTotal, byte Lane, ulong? HardwareTime, long SoftwareTime, DateTime UtcTime);
public record OpenPracticePilotDetectionTriggered(Guid DetectionId, Guid SessionId, Guid TrackId, Guid PilotId, byte Lane, byte OrdinalPosition, byte TrackDetectorCount, ulong? HardwareTime, long SoftwareTime, DateTime UtcTime);
public record OpenPracticePilotDetectionTriggeredToCloseToPreviousDetection(Guid DetectionId, Guid SessionId, Guid TrackId, Guid PilotId, byte Lane, ulong? HardwareTime, long SoftwareTime, DateTime UtcTime, Guid ConflictDetectionId, Guid? ConflictDetectionTimerId, byte ConclictDetectionLane, ulong? ConflictDetectionHardwareTime, long ConflictDetectionSoftwareTime, DateTime ConflictDetectionUtcTime);
public record OpenPracticePilotDetectionOccuredToCloseToPreviousDetection(Guid DetectionId, Guid SessionId, Guid TrackId, Guid PilotId, Guid TimerId, byte Lane, ulong? HardwareTime, long SoftwareTime, DateTime UtcTime, Guid ConflictDetectionId, Guid? ConflictDetectionTimerId, byte ConclictDetectionLane, ulong? ConflictDetectionHardwareTime, long ConflictDetectionSoftwareTime, DateTime ConflictDetectionUtcTime);
public record OpenPracticePilotDetectionOccuredOutOfOrder(Guid DetectionId, Guid SessionId, Guid TrackId, Guid PilotId, Guid TimerId, byte TrackTimerOrdinal, byte TrackTimerTotal, byte Lane, ulong? HardwareTime, long SoftwareTime, DateTime UtcTime);
public record OpenPracticePilotDetectionTriggeredOutOfOrder(Guid DetectionId, Guid SessionId, Guid TrackId, Guid PilotId, byte OrdinalPosition, byte TrackDetectorCount, ulong? HardwareTime, long SoftwareTime, DateTime UtcTime);
public record OpenPracticePilotDetectionOccuredOnInvalidTimer(Guid DetectionId, Guid SessionId, Guid TrackId, Guid PilotId, Guid TimerId, byte Lane, ulong? HardwareTime, long SoftwareTime, DateTime UtcTime);