// <auto-generated />
using System;
using EventDb.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventDbLite.Migrations
{
    [DbContext(typeof(EventDbLiteContext))]
    [Migration("20250605155403_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("EventDbLite.DbModels.PersistedEvent", b =>
                {
                    b.Property<long>("GlobalOrdinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Metadata")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("StreamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StreamOrdinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("GlobalOrdinal");

                    b.HasIndex("StreamName");

                    b.HasIndex("StreamName", "StreamOrdinal")
                        .IsUnique();

                    b.ToTable("PersistedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
