<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NaeTime.Hardware.ImmersionRC\NaeTime.Hardware.ImmersionRC.csproj" />
    <ProjectReference Include="..\NaeTime.Hardware.Node.Esp32\NaeTime.Hardware.Node.Esp32.csproj" />
    <ProjectReference Include="..\NaeTime.Orchestrator.Abstractions\NaeTime.Orchestrator.Abstractions.csproj" />
    <ProjectReference Include="..\NaeTime.Orchestrator.Distribution.Abstractions\NaeTime.Orchestrator.Distribution.Abstractions.csproj" />
    <ProjectReference Include="..\NaeTime.Orchestrator.Persistence.Abstractions\NaeTime.Orchestrator.Persistence.Abstractions.csproj" />
    <ProjectReference Include="..\NaeTime.Persistence.Abstractions\NaeTime.Persistence.Abstractions.csproj" />
  </ItemGroup>

</Project>
